In [1]:
import os
import pandas as pd
from pathlib import Path

In [2]:
df = pd.read_excel('../templates/T-Shirts(mens-Fashion-tshirts).xlsm', sheet_name="Template", header=None) 
first_2_rows = df.loc[:2,:]
df = pd.read_excel('../templates/T-Shirts(mens-Fashion-tshirts).xlsm', sheet_name="Template", skiprows=2) 
fields = pd.read_excel('../templates/T-Shirts(mens-Fashion-tshirts).xlsm', sheet_name="Data Definitions", skiprows=1).fillna(method='ffill').drop(0)
valid_values = pd.read_excel("../templates/T-Shirts(mens-Fashion-tshirts).xlsm", sheet_name="Valid Values", skiprows=1, header=None).set_index(1).drop(0,axis=1)

In [9]:
dtypes = df.dtypes

In [10]:
df.astype(dtypes)

,feed_product_type,item_sku,brand_name,external_product_id,external_product_id_type,item_name,recommended_browse_nodes,outer_material_type,color_map,color_name,...,progressive_discount_type,progressive_discount_lower_bound1,progressive_discount_value1,progressive_discount_lower_bound2,progressive_discount_value2,progressive_discount_lower_bound3,progressive_discount_value3,national_stock_number,unspsc_code,pricing_action
0,shirt,NaN,The Shirt Shack,NaN,NaN,NaN,1731028031,Cotton,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df["quantity"].astype("Int64")

0     999
1    <NA>
Name: quantity, dtype: Int64

In [21]:
dtypes[dtypes == 'int6'] = 'Int64'

In [22]:
df.astype(dtypes[dtypes == 'Int64'])

,feed_product_type,item_sku,brand_name,external_product_id,external_product_id_type,item_name,recommended_browse_nodes,outer_material_type,color_map,color_name,...,progressive_discount_type,progressive_discount_lower_bound1,progressive_discount_value1,progressive_discount_lower_bound2,progressive_discount_value2,progressive_discount_lower_bound3,progressive_discount_value3,national_stock_number,unspsc_code,pricing_action
0,shirt,NaN,The Shirt Shack,NaN,NaN,NaN,1.731028e+09,Cotton,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.dtypes

feed_product_type                     object
item_sku                             float64
brand_name                            object
external_product_id                  float64
external_product_id_type             float64
                                      ...
progressive_discount_lower_bound3    float64
progressive_discount_value3          float64
national_stock_number                float64
unspsc_code                          float64
pricing_action                       float64
Length: 205, dtype: object

In [57]:
valid_values = valid_values.apply(lambda x: x.dropna().to_list(), axis=1)

In [58]:
valid_values.index = valid_values.index.str.replace(r' - .*', '', regex=True)

In [59]:
valid_values = valid_values[valid_values.str.len()>0]

In [62]:
valid_values[~valid_values.index.duplicated()]

1
Product Type                                                           [shirt]
Brand Name                                                   [The Shirt Shack]
Product ID Type                                   [GTIN, EAN, GCID, UPC, ASIN]
Recommended Browse Nodes                                          [1731028031]
Outer Material Type          [Alpaca, Angora, Cashmere, Corduroy, Cotton, D...
                                                   ...
Merchant Shipping Group                  [Migrated Template, Nationwide Prime]
Product Tax Code             [A_BABY_BIBCLOTH, A_BABY_CARSEAT, A_BABY_NAPPI...
Quantity Price Type                                           [fixed, percent]
Progressive Discount Type                                     [fixed, percent]
Pricing Action               [delete business_price, delete quantity_price,...
Length: 78, dtype: object

In [54]:
fields[["Field name", "Local label name"]].set_index("Field name")["Local label name"].to_dict()

{'feed_product_type': 'Product Type',
 'item_sku': 'Seller SKU',
 'brand_name': 'Brand Name',
 'external_product_id': 'Product ID',
 'external_product_id_type': 'Product ID Type',
 'item_name': 'Product Name',
 'recommended_browse_nodes': 'Recommended Browse Nodes',
 'outer_material_type': 'Outer Material Type',
 'color_map': 'Colour Map',
 'color_name': 'Colour',
 'size_name': 'Size',
 'department_name': 'Department',
 'size_map': 'Size Map',
 'country_of_origin': 'Country/Region Of Origin',
 'fabric_type': 'Fabric type',
 'standard_price': 'Your Price',
 'quantity': 'Quantity',
 'main_image_url': 'Main Image Url',
 'target_gender': 'Target Gender',
 'age_range_description': 'Age Range Description',
 'shirt_size_system': 'Shirt Size System',
 'shirt_size_class': 'Shirt Size Class',
 'shirt_size': 'Shirt Size Value',
 'shirt_size_to': 'Shirt Size To Range',
 'shirt_neck_size': 'Neck Size Value',
 'shirt_neck_size_to': 'Neck Size To Value',
 'shirt_sleeve_length': 'Sleeve Length Value',
 'shirt_sleeve_length_to': 'Sleeve Length To Value',
 'shirt_body_type': 'Shirt Body Type',
 'shirt_height_type': 'Shirt Height Type',
 'other_image_url1': 'Other Image Url1',
 'other_image_url_ps01': 'other image url ps01',
 'other_image_url1 - other_image_url8': 'Other Image Url',
 'swatch_image_url': 'Swatch Image Url',
 'parent_child': 'Parentage',
 'parent_sku': 'Parent SKU',
 'relationship_type': 'Relationship Type',
 'variation_theme': 'Variation Theme',
 'package_level': 'Package Level',
 'package_contains_quantity': 'Package Contains Quantity',
 'package_contains_identifier': 'Package Contains Identifier',
 'update_delete': 'Update Delete',
 'product_description': 'Product Description',
 'inner_material_type': 'Inner Material Type',
 'care_instructions': 'Product Care Instructions',
 'model_name': 'Model Name',
 'model': 'Model Number',
 'closure_type': 'Closure Type',
 'part_number': 'Manufacturer Part Number',
 'item_type': 'Item Type',
 'manufacturer': 'Manufacturer',
 'gtin_exemption_reason': 'Product Exemption Reason',
 'language_value1 - language_value5': 'Language',
 'generic_keywords': 'Search Terms',
 'collection_name': 'Season and collection year',
 'pattern_type': 'Pattern description',
 'lifestyle': 'Occasion description',
 'style_name': 'Style Name',
 'collar_style': 'Collar Style',
 'fit_type': 'Fitting type',
 'special_features1 - special_features5': 'Special Features',
 'bullet_point1 - bullet_point5': 'Key Product Features',
 'special_size_type': 'size-modifier',
 'platinum_keywords1 - platinum_keywords5': 'platinum-keywords1 - platinum-keywords5',
 'is_autographed': 'Is Autographed',
 'item_type_name': 'Item Type Name',
 'occasion_type1 - occasion_type5': 'Occasion Type',
 'sport_type1 - sport_type2': 'Sport Type',
 'seasons': 'Season',
 'athlete': 'Athlete',
 'team_name': 'Team Name',
 'material_type': 'Material Type',
 'fur_description': 'Fur Description',
 'weave_type': 'Weave Type',
 'theme': 'Theme',
 'league_name': 'League Name',
 'shaft_style_type': 'Shaft Style Type',
 'lifecycle_supply_type': 'Product Lifecycle Supply Type',
 'pattern_name': 'Pattern',
 'item_booking_date': 'Item Booking Date',
 'sleeve_type': 'Sleeve Type',
 'subject_character': 'Subject Character',
 'flash_point_unit_of_measure': 'flash_point_unit_of_measure',
 'neck_size': 'Neck size',
 'neck_size_unit_of_measure': 'Neck Size unit',
 'item_length_description': 'Item Length',
 'cup_size': 'Bra cup size',
 'website_shipping_weight': 'Shipping Weight',
 'website_shipping_weight_unit_of_measure': 'Website Shipping Weight Unit Of Measure',
 'item_width_unit_of_measure': 'Item Width Unit Of Measure',
 'item_width': 'Item Width',
 'item_height': 'Item Height',
 'item_shape': 'Item Shape',
 'item_height_unit_of_measure': 'Item Height Unit Of Measure',
 'item_length_unit_of_measure': 'Item Length Unit Of Measure',
 'item_length': 'Item Length',
 'legal_disclaimer_description': 'Legal Disclaimer Description',
 'safety_warning': 'Safety Warning',
 'eu_toys_safety_directive_age_warning': 'EU Toys Safety Directive Age-specific warning',
 'eu_toys_safety_directive_warning': 'EU Toys Safety Directive Non-Age-specific warning',
 'eu_toys_safety_directive_language': 'EU Toys Safety Directive language warning',
 'batteries_required': 'Is this product a battery or does it utilise batteries?',
 'are_batteries_included': 'Batteries are Included',
 'battery_type1 - battery_type3': 'Battery type/size',
 'number_of_batteries1 - number_of_batteries3': 'Number of batteries',
 'number_of_lithium_metal_cells': 'Number of Lithium Metal Cells',
 'number_of_lithium_ion_cells': 'Number of Lithium-ion Cells',
 'lithium_battery_packaging': 'Lithium Battery Packaging',
 'lithium_battery_energy_content': 'Watt hours per battery',
 'lithium_battery_energy_content_unit_of_measure': 'lithium_battery_energy_content_unit_of_measure',
 'lithium_battery_weight': 'Lithium content (grams)',
 'lithium_battery_weight_unit_of_measure': 'lithium_battery_weight_unit_of_measure',
 'item_weight': 'Item Weight',
 'item_weight_unit_of_measure': 'item_weight_unit_of_measure',
 'item_volume': 'Volume',
 'item_volume_unit_of_measure': 'item_volume_unit_of_measure',
 'supplier_declared_material_regulation1 - supplier_declared_material_regulation3': 'Material/Fabric Regulations',
 'condition_type': 'Condition Type',
 'condition_note': 'Condition Note',
 'currency': 'Currency',
 'fulfillment_latency': 'Handling Time',
 'sale_price': 'Sale Price',
 'sale_from_date': 'Sale From Date',
 'sale_end_date': 'Sale End Date',
 'max_aggregate_ship_quantity': 'max-aggregate-ship-quantity',
 'item_package_quantity': 'Package Quantity',
 'number_of_items': 'Number of Items',
 'offering_can_be_gift_messaged': 'Can Be Gift Messaged',
 'offering_can_be_giftwrapped': 'Is Gift Wrap Available?',
 'is_discontinued_by_manufacturer': 'Is Discontinued by Manufacturer',
 'product_site_launch_date': 'Launch Date',
 'restock_date': 'Restock Date',
 'map_price': 'Minimum Advertised Price',
 'list_price_with_tax': 'List Price with Tax for Display',
 'merchant_release_date': 'Release Date',
 'list_price': 'Recommended Retail Price',
 'offering_end_date': 'Offer End Date',
 'max_order_quantity': 'Max Order Quantity',
 'merchant_shipping_group_name': 'Merchant Shipping Group',
 'offering_start_date': 'Offer Start Date',
 'liquidate_remainder': 'Sell Remainder',
 'delivery_schedule_group_id': 'Scheduled Delivery SKU List',
 'uvp_list_price': 'RRP',
 'product_tax_code': 'Product Tax Code',
 'minimum_order_quantity_minimum': 'Minimum Order Quantity',
 'business_price': 'Business Price',
 'quantity_price_type': 'Quantity Price Type',
 'quantity_lower_bound1': 'Quantity Lower Bound 1',
 'quantity_price1': 'Quantity Price 1',
 'progressive_discount_type': 'Progressive Discount Type',
 'progressive_discount_lower_bound1': 'Progressive Discount Lower Bound 1',
 'progressive_discount_value1': 'Progressive Discount Value 1',
 'national_stock_number': 'National Stock Number',
 'unspsc_code': 'United Nations Standard Products and Services Code',
 'pricing_action': 'Pricing Action'}

In [4]:
first_row = df.loc[0, :].copy()

In [6]:
first_row.update({"brand_name": "brand_name"})

In [7]:
first_row

feed_product_type                         shirt
item_sku                                    NaN
brand_name                           brand_name
external_product_id                         NaN
external_product_id_type                    NaN
                                        ...
progressive_discount_lower_bound3           NaN
progressive_discount_value3                 NaN
national_stock_number                       NaN
unspsc_code                                 NaN
pricing_action                              NaN
Name: 0, Length: 205, dtype: object